theme: jekyll-theme-minimal
title: 'Spatial Transcritomics Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome

  - heading: Support
  - title: Schedule
    url: base/schedule
  - title: Slack
    url: base/slack
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links
  - title: GitHub repository
    url: https://github.com/ucdavis-bioinformatics-training/2025-March-Spatial-Transcriptomics
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites_fixed

  - heading: Data Reduction
  - title: Files and Filetypes
    url: data_reduction/filetypes
  - title: Project setup
    url: data_reduction/project_setup
  - title: Generating Expression Matrix
    url: data_reduction/Expression_Matrix

  - heading: Spatial Transcriptomics
  - title: Technologies
    url: data_reduction/Introduction_to_Spatial_Transcriptomics

  - heading: scRNAseq Analysis
  - title: Prepare scRNAseq Analysis
    url: data_analysis/00-prepare
  - title: Part 1- Create object
    url: data_analysis/01-create_object
  - title: Part 2- Filtering
    url: data_analysis/02-filtering
  - title: Part 3- Normalization and scaling
    url: data_analysis/03-normalize_scale
  - title: Part 4- Dimensionality reduction
    url: data_analysis/04-dimensionality_reduction
  - title: Part 5- Clustering and cell type
    url: data_analysis/05-clustering_celltype
  - title: Part 6- Enrichment and DE
    url: data_analysis/06-de_enrichment
  - title: Part 7- Doublet detection
    url: data_analysis/07-doublet_detection
  - title: Part 8- Integration
    url: data_analysis/08-integration
