theme: jekyll-theme-minimal
title: 'Spatial Transcriptomics Analysis'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome

  - heading: Support
  - title: Schedule
    url: base/schedule
  - title: Slack
    url: base/slack
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links
  - title: GitHub repository
    url: https://github.com/ucdavis-bioinformatics-training/2025-March-Spatial-Transcriptomics
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu

  - heading: Prerequisites
  - title: CLI
    url: base/cli_prerequisites
  - title: R
    url: base/r_prerequisites_fixed

  - heading: Spatial Transcriptomics
  - title: Technologies
    url: data_reduction/Introduction_to_Spatial_Transcriptomics
  - title: Introduction to Data
    url: data_reduction/Introduction_to_data
  - title: Part 0- Prepare R Env
    url: data_reduction/00-prepare
  - title: Part 1- Data Exploration
    url: data_reduction/01-Data_exploration
  - title: Part 2- Clustering
    url: data_reduction/02-Clustering
  - title: Part 3- Cell type
    url: data_reduction/03-Celltype
  - title: Part 4- Niche
    url: data_reduction/04-Simple_Niche
  - title: Part 5- NicheDE
    url: data_reduction/05-Niche

